baseURL: "https://0ozero0.github.io/"
title: "~Zero"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# إذا تملك Google Analytics 4 استبدل Measurement ID الخاص بك هنا
# googleAnalytics: "G-XXXXXXXXXX"
googleAnalytics: UA-123-45  # مثال قديم - استبدله أو علّقه إذا تستخدم GA4

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # لتفعيل التحليلات وopen graph وtwitter cards وschema
  title: Zero
  description: "Zero description"
  keywords: [Blog, Portfolio, Security Researcher]
  author: Zero
  # author: ["Me", "You"] # في حال وجود مؤلفين متعددين
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # الخيارات: dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: true

  assets:
    # يمكنك إضافة روابط أيقونات حقيقية هنا بدل <link / abs url>
    favicon: "https://i.ibb.co/fG1ndSd/no-clue.png"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Zero"
    icon: /apple-touch-icon.png
    iconHeight: 35

  profileMode:
    enabled: true
    title: Intro
    subtitle: "I'm Ahmed Muhammed | AKA zero | Security Researcher - Bug Hunter - CTF player"
    imageUrl: "https://i.imgur.com/1LYnfCU.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: My PiC
    buttons:
      - name: Write-ups
        url: write-ups
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: "Welcome to my blog, I'm Zero Security Researcher -CTF player"

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/ahmed-muhammed-709429242"
    - name: facebook
      url: "https://www.facebook.com/profile.php?id=100012719656071"

  analytics:
    google:
      SiteVerificationTag: "CTFS - Security Blog | Hacking"
    bing:
      SiteVerificationTag: "CTFS - Security Blog | Hacking"
    yandex:
      SiteVerificationTag: "CTFS - Security Blog | Hacking"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: Write-ups
      name: write-ups
      url: /write-ups/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weight: 10

pygmentsUseClasses: true

markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON  # ضروري لعمل البحث حسب الوثائق

# أضفت هنا taxonomy social لو حبيت تضيف social كتصنيفات بدل استخدام .Site.Social
taxonomies:
  social: "social"
